distributed.nanny - INFO -         Start Nanny at: 'tcp://10.10.15.9:43141'
distributed.diskutils - INFO - Found stale lock file and directory '/users/k1201869/wang_model/code/model_fitting/dask-worker-space/dask-worker-space/worker-km7croxb', purging
distributed.diskutils - INFO - Found stale lock file and directory '/users/k1201869/wang_model/code/model_fitting/dask-worker-space/dask-worker-space/worker-l8u18u89', purging
distributed.diskutils - INFO - Found stale lock file and directory '/users/k1201869/wang_model/code/model_fitting/dask-worker-space/dask-worker-space/worker-jnrqcagz', purging
distributed.diskutils - INFO - Found stale lock file and directory '/users/k1201869/wang_model/code/model_fitting/dask-worker-space/dask-worker-space/worker-dtxy_xoh', purging
distributed.diskutils - INFO - Found stale lock file and directory '/users/k1201869/wang_model/code/model_fitting/dask-worker-space/dask-worker-space/worker-kylofd5l', purging
distributed.diskutils - INFO - Found stale lock file and directory '/users/k1201869/wang_model/code/model_fitting/dask-worker-space/dask-worker-space/worker-g1jz_ib5', purging
distributed.diskutils - INFO - Found stale lock file and directory '/users/k1201869/wang_model/code/model_fitting/dask-worker-space/dask-worker-space/worker-ffcr0n6x', purging
distributed.diskutils - INFO - Found stale lock file and directory '/users/k1201869/wang_model/code/model_fitting/dask-worker-space/dask-worker-space/worker-jw5t5_6t', purging
distributed.diskutils - INFO - Found stale lock file and directory '/users/k1201869/wang_model/code/model_fitting/dask-worker-space/dask-worker-space/worker-bhtdnvxx', purging
distributed.diskutils - INFO - Found stale lock file and directory '/users/k1201869/wang_model/code/model_fitting/dask-worker-space/dask-worker-space/worker-85apk68_', purging
distributed.diskutils - INFO - Found stale lock file and directory '/users/k1201869/wang_model/code/model_fitting/dask-worker-space/dask-worker-space/worker-we5r79i3', purging
distributed.diskutils - INFO - Found stale lock file and directory '/users/k1201869/wang_model/code/model_fitting/dask-worker-space/dask-worker-space/worker-2izye1um', purging
distributed.diskutils - INFO - Found stale lock file and directory '/users/k1201869/wang_model/code/model_fitting/dask-worker-space/dask-worker-space/worker-ub59nyhz', purging
distributed.diskutils - INFO - Found stale lock file and directory '/users/k1201869/wang_model/code/model_fitting/dask-worker-space/dask-worker-space/worker-jw34r2bg', purging
distributed.diskutils - INFO - Found stale lock file and directory '/users/k1201869/wang_model/code/model_fitting/dask-worker-space/dask-worker-space/worker-55gg97ua', purging
distributed.worker - INFO -       Start worker at:     tcp://10.10.15.9:35641
distributed.worker - INFO -          Listening to:     tcp://10.10.15.9:35641
distributed.worker - INFO -          dashboard at:           10.10.15.9:32833
distributed.worker - INFO - Waiting to connect to:    tcp://10.10.15.13:45716
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    2.00 GB
distributed.worker - INFO -       Local Directory: /users/k1201869/wang_model/code/model_fitting/dask-worker-space/dask-worker-space/worker-ooja9skg
distributed.worker - INFO - -------------------------------------------------
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://10.10.15.9:50932 remote=tcp://10.10.15.13:45716>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://10.10.15.9:50936 remote=tcp://10.10.15.13:45716>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://10.10.15.9:50938 remote=tcp://10.10.15.13:45716>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://10.10.15.9:50940 remote=tcp://10.10.15.13:45716>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://10.10.15.9:50944 remote=tcp://10.10.15.13:45716>
distributed.worker - INFO - Waiting to connect to:    tcp://10.10.15.13:45716
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://10.10.15.9:50974 remote=tcp://10.10.15.13:45716>
distributed.worker - INFO - Waiting to connect to:    tcp://10.10.15.13:45716
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://10.10.15.9:50980 remote=tcp://10.10.15.13:45716>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://10.10.15.9:50984 remote=tcp://10.10.15.13:45716>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://10.10.15.9:50990 remote=tcp://10.10.15.13:45716>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://10.10.15.9:51010 remote=tcp://10.10.15.13:45716>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://10.10.15.9:51028 remote=tcp://10.10.15.13:45716>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://10.10.15.9:51034 remote=tcp://10.10.15.13:45716>
distributed.worker - INFO - Waiting to connect to:    tcp://10.10.15.13:45716
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://10.10.15.9:51040 remote=tcp://10.10.15.13:45716>
distributed.worker - INFO - Waiting to connect to:    tcp://10.10.15.13:45716
distributed.worker - INFO - Waiting to connect to:    tcp://10.10.15.13:45716
distributed.nanny - INFO - Closing Nanny at 'tcp://10.10.15.9:43141'
distributed.worker - INFO - Stopping worker at tcp://10.10.15.9:35641
distributed.worker - INFO - Closed worker has not yet started: Status.undefined
distributed.dask_worker - INFO - End worker
Traceback (most recent call last):
  File "/users/k1201869/miniconda3/envs/python38/lib/python3.8/site-packages/distributed/core.py", line 295, in _
    await asyncio.wait_for(self.start(), timeout=timeout)
  File "/users/k1201869/miniconda3/envs/python38/lib/python3.8/asyncio/tasks.py", line 490, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/users/k1201869/miniconda3/envs/python38/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/users/k1201869/miniconda3/envs/python38/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/users/k1201869/miniconda3/envs/python38/lib/python3.8/site-packages/distributed/cli/dask_worker.py", line 460, in <module>
    go()
  File "/users/k1201869/miniconda3/envs/python38/lib/python3.8/site-packages/distributed/cli/dask_worker.py", line 456, in go
    main()
  File "/users/k1201869/miniconda3/envs/python38/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/users/k1201869/miniconda3/envs/python38/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/users/k1201869/miniconda3/envs/python38/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/users/k1201869/miniconda3/envs/python38/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/users/k1201869/miniconda3/envs/python38/lib/python3.8/site-packages/distributed/cli/dask_worker.py", line 442, in main
    loop.run_sync(run)
  File "/users/k1201869/miniconda3/envs/python38/lib/python3.8/site-packages/tornado/ioloop.py", line 532, in run_sync
    return future_cell[0].result()
  File "/users/k1201869/miniconda3/envs/python38/lib/python3.8/site-packages/distributed/cli/dask_worker.py", line 436, in run
    await asyncio.gather(*nannies)
  File "/users/k1201869/miniconda3/envs/python38/lib/python3.8/asyncio/tasks.py", line 684, in _wrap_awaitable
    return (yield from awaitable.__await__())
  File "/users/k1201869/miniconda3/envs/python38/lib/python3.8/site-packages/distributed/core.py", line 299, in _
    raise TimeoutError(
asyncio.exceptions.TimeoutError: Nanny failed to start in 60 seconds
