distributed.nanny - INFO -         Start Nanny at: 'tcp://10.10.18.6:33993'
distributed.diskutils - INFO - Found stale lock file and directory '/users/k1201869/wang_model/code/model_fitting/dask-worker-space/dask-worker-space/worker-9jhpalw3', purging
distributed.diskutils - INFO - Found stale lock file and directory '/users/k1201869/wang_model/code/model_fitting/dask-worker-space/dask-worker-space/worker-blq_wvvo', purging
distributed.diskutils - INFO - Found stale lock file and directory '/users/k1201869/wang_model/code/model_fitting/dask-worker-space/dask-worker-space/worker-l_sdwqh3', purging
distributed.diskutils - INFO - Found stale lock file and directory '/users/k1201869/wang_model/code/model_fitting/dask-worker-space/dask-worker-space/worker-c2uqp2v1', purging
distributed.diskutils - INFO - Found stale lock file and directory '/users/k1201869/wang_model/code/model_fitting/dask-worker-space/dask-worker-space/worker-12i6fk4n', purging
distributed.diskutils - INFO - Found stale lock file and directory '/users/k1201869/wang_model/code/model_fitting/dask-worker-space/dask-worker-space/worker-nv9fx6iu', purging
distributed.diskutils - INFO - Found stale lock file and directory '/users/k1201869/wang_model/code/model_fitting/dask-worker-space/dask-worker-space/worker-2lukr9xv', purging
distributed.diskutils - INFO - Found stale lock file and directory '/users/k1201869/wang_model/code/model_fitting/dask-worker-space/dask-worker-space/worker-0qd2ljkx', purging
distributed.diskutils - INFO - Found stale lock file and directory '/users/k1201869/wang_model/code/model_fitting/dask-worker-space/dask-worker-space/worker-d0i_a8en', purging
distributed.worker - INFO -       Start worker at:     tcp://10.10.18.6:45419
distributed.worker - INFO -          Listening to:     tcp://10.10.18.6:45419
distributed.worker - INFO -          dashboard at:           10.10.18.6:46667
distributed.worker - INFO - Waiting to connect to:    tcp://10.10.18.12:42630
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    2.00 GB
distributed.worker - INFO -       Local Directory: /users/k1201869/wang_model/code/model_fitting/dask-worker-space/dask-worker-space/worker-zkhckb6i
distributed.worker - INFO - -------------------------------------------------
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://10.10.18.6:49572 remote=tcp://10.10.18.12:42630>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://10.10.18.6:49574 remote=tcp://10.10.18.12:42630>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://10.10.18.6:49576 remote=tcp://10.10.18.12:42630>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://10.10.18.6:49580 remote=tcp://10.10.18.12:42630>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://10.10.18.6:49582 remote=tcp://10.10.18.12:42630>
distributed.worker - INFO - Waiting to connect to:    tcp://10.10.18.12:42630
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://10.10.18.6:49586 remote=tcp://10.10.18.12:42630>
distributed.worker - INFO - Waiting to connect to:    tcp://10.10.18.12:42630
distributed.worker - INFO - Waiting to connect to:    tcp://10.10.18.12:42630
distributed.worker - INFO - Waiting to connect to:    tcp://10.10.18.12:42630
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://10.10.18.6:49638 remote=tcp://10.10.18.12:42630>
distributed.worker - INFO - Waiting to connect to:    tcp://10.10.18.12:42630
distributed.nanny - INFO - Closing Nanny at 'tcp://10.10.18.6:33993'
distributed.worker - INFO - Stopping worker at tcp://10.10.18.6:45419
distributed.worker - INFO - Closed worker has not yet started: Status.undefined
distributed.dask_worker - INFO - End worker
Traceback (most recent call last):
  File "/users/k1201869/miniconda3/envs/python38/lib/python3.8/site-packages/distributed/core.py", line 295, in _
    await asyncio.wait_for(self.start(), timeout=timeout)
  File "/users/k1201869/miniconda3/envs/python38/lib/python3.8/asyncio/tasks.py", line 490, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/users/k1201869/miniconda3/envs/python38/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/users/k1201869/miniconda3/envs/python38/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/users/k1201869/miniconda3/envs/python38/lib/python3.8/site-packages/distributed/cli/dask_worker.py", line 460, in <module>
    go()
  File "/users/k1201869/miniconda3/envs/python38/lib/python3.8/site-packages/distributed/cli/dask_worker.py", line 456, in go
    main()
  File "/users/k1201869/miniconda3/envs/python38/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/users/k1201869/miniconda3/envs/python38/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/users/k1201869/miniconda3/envs/python38/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/users/k1201869/miniconda3/envs/python38/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/users/k1201869/miniconda3/envs/python38/lib/python3.8/site-packages/distributed/cli/dask_worker.py", line 442, in main
    loop.run_sync(run)
  File "/users/k1201869/miniconda3/envs/python38/lib/python3.8/site-packages/tornado/ioloop.py", line 532, in run_sync
    return future_cell[0].result()
  File "/users/k1201869/miniconda3/envs/python38/lib/python3.8/site-packages/distributed/cli/dask_worker.py", line 436, in run
    await asyncio.gather(*nannies)
  File "/users/k1201869/miniconda3/envs/python38/lib/python3.8/asyncio/tasks.py", line 684, in _wrap_awaitable
    return (yield from awaitable.__await__())
  File "/users/k1201869/miniconda3/envs/python38/lib/python3.8/site-packages/distributed/core.py", line 299, in _
    raise TimeoutError(
asyncio.exceptions.TimeoutError: Nanny failed to start in 60 seconds
