28
subject 185442
loaded saved variables
version 3
102
/users/k1201869/miniconda3/envs/python38/lib/python3.8/site-packages/distributed/node.py:151: UserWarning: Port 8787 is already in use.
Perhaps you already have a cluster running?
Hosting the HTTP server on port 34855 instead
  warnings.warn(
parrallel submitted 09:01:36
parrallel finished 09:05:53
estimation_imag_fix_testretest.py:217: ComplexWarning: Casting complex values to real discards the imaginary part
  inv_JinvCeJ[i,:] = J[:,i].T * inv_DiagCe
estimation_imag_fix_testretest.py:230: ComplexWarning: Casting complex values to real discards the imaginary part
  P[:,i] = (J[:,i]*np.squeeze(inv_DiagCe))
estimation_imag_fix_testretest.py:250: ComplexWarning: Casting complex values to real discards the imaginary part
  g[i] = -0.5*np.exp(lembda[i])*np.trace(P[T*i:T*i+T][:, T*i:T*i+T])
estimation_imag_fix_testretest.py:255: ComplexWarning: Casting complex values to real discards the imaginary part
  g[i] = g[i] + g_rest
/users/k1201869/wang_model/code/model_fitting/wang_functions_imag_fix.py:502: ComplexWarning: Casting complex values to real discards the imaginary part
  tr[i] = np.sum(temp)
/users/k1201869/miniconda3/envs/python38/lib/python3.8/site-packages/numpy/core/fromnumeric.py:87: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
[[-2.00212605]]
estimation_imag_fix_testretest.py:309: ComplexWarning: Casting complex values to real discards the imaginary part
  JinvCe[i,:] = J[:,i] * inv_DiagCe #;% J'%invCe <----- p x nT
estimation_imag_fix_testretest.py:320: ComplexWarning: Casting complex values to real discards the imaginary part
  A_FDK[:,ppi] = np.squeeze(A) + np.squeeze(d_A) # %newton-gauss, fisher scoring, update Para_E
distributed.client - ERROR - Failed to reconnect to scheduler after 10.00 seconds, closing client
_GatheringFuture exception was never retrieved
future: <_GatheringFuture finished exception=CancelledError()>
asyncio.exceptions.CancelledError
estimation_imag_fix_testretest.py:331: ComplexWarning: Casting complex values to real discards the imaginary part
  h_output_FDK[:,ppi], CC_check_FDK[ppi] = funcP(np.atleast_2d(Para_E_new).T)
estimation_imag_fix_testretest.py:334: ComplexWarning: Casting complex values to real discards the imaginary part
  dlddpara_FDK[:,:,ppi] = dlddpara
estimation_imag_fix_testretest.py:335: ComplexWarning: Casting complex values to real discards the imaginary part
  dldpara_FDK[:,ppi] = dldpara
[[-1.94007298]]
/users/k1201869/wang_model/code/model_fitting/wang_functions_imag_fix.py:517: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  sol = np.linalg.lstsq(A, b)[0]    # not under-determined
real won
goodness of fit correlation [0.05576778]
0.4164770824677805
[5.22446375e-01 5.08569482e-01 5.14461329e-01 5.06386605e-01
 4.96625671e-01 5.17862577e-01 5.38610864e-01 5.50438827e-01
 5.00591162e-01 5.26424838e-01 5.11009197e-01 5.13885702e-01
 5.13582098e-01 5.29282601e-01 5.21923346e-01 5.15873347e-01
 5.27726084e-01 5.02273013e-01 5.15941537e-01 5.27956137e-01
 6.27256427e-01 5.17730496e-01 5.73773319e-01 5.13109134e-01
 5.18450457e-01 5.05130335e-01 5.18552795e-01 5.54396659e-01
 5.16964284e-01 5.96066430e-01 4.94695962e-01 5.03336563e-01
 5.02463644e-01 5.53678020e-01 5.15729854e-01 5.18147816e-01
 5.03049677e-01 5.22410050e-01 4.96847982e-01 5.34778598e-01
 5.51756306e-01 5.42233155e-01 5.01879741e-01 5.36049299e-01
 5.17188563e-01 5.30393339e-01 5.14376015e-01 5.43059210e-01
 5.20451560e-01 5.29555322e-01 5.10316548e-01 5.04854718e-01
 5.28133786e-01 5.30014016e-01 5.96990495e-01 5.19610851e-01
 5.31192464e-01 5.13596209e-01 5.14186350e-01 5.05589678e-01
 5.07151005e-01 5.33967619e-01 5.27665472e-01 5.72477805e-01
 5.01878356e-01 5.02634438e-01 5.01830240e-01 5.16378732e-01
 3.38404253e-01 3.22478443e-01 3.38062721e-01 3.55903149e-01
 3.19548382e-01 3.55308378e-01 3.35689690e-01 3.48181947e-01
 3.27444090e-01 3.62708339e-01 3.30865241e-01 3.43698001e-01
 3.26721659e-01 3.40039562e-01 3.32954583e-01 3.52124701e-01
 3.45572785e-01 3.29247476e-01 3.33028792e-01 3.59203911e-01
 3.38423775e-01 3.27950252e-01 3.36572722e-01 3.47197969e-01
 3.26197270e-01 3.41355744e-01 3.16775633e-01 3.29972657e-01
 3.58249300e-01 3.35568305e-01 3.15484396e-01 3.25645896e-01
 3.67516146e-01 3.42052640e-01 3.49934033e-01 3.29907313e-01
 3.39783982e-01 3.61526773e-01 3.20339801e-01 3.45837382e-01
 3.29386020e-01 3.45271070e-01 3.38578036e-01 3.68057013e-01
 3.30168639e-01 3.58912325e-01 3.27689152e-01 3.45228083e-01
 3.43966248e-01 3.52481363e-01 3.43367864e-01 3.24835394e-01
 3.40974672e-01 3.55515540e-01 3.36824708e-01 3.42780916e-01
 3.37439938e-01 3.45401422e-01 3.23029458e-01 3.48055870e-01
 3.15241665e-01 3.36223954e-01 3.28896885e-01 3.41586668e-01
 3.16780819e-01 3.12112652e-01 3.47097725e-01 3.44087663e-01
 1.59727896e+00 1.01199851e-03]
version 4
0
/users/k1201869/miniconda3/envs/python38/lib/python3.8/site-packages/distributed/node.py:151: UserWarning: Port 8787 is already in use.
Perhaps you already have a cluster running?
Hosting the HTTP server on port 34661 instead
  warnings.warn(
parrallel submitted 09:06:44
