distributed.nanny - INFO -         Start Nanny at: 'tcp://10.10.15.24:42625'
distributed.diskutils - INFO - Found stale lock file and directory '/users/k1201869/wang_model/code/model_fitting/dask-worker-space/dask-worker-space/worker-t5swb9l_', purging
distributed.diskutils - INFO - Found stale lock file and directory '/users/k1201869/wang_model/code/model_fitting/dask-worker-space/dask-worker-space/worker-7syp2z58', purging
distributed.diskutils - INFO - Found stale lock file and directory '/users/k1201869/wang_model/code/model_fitting/dask-worker-space/dask-worker-space/worker-s2dwks2j', purging
distributed.diskutils - INFO - Found stale lock file and directory '/users/k1201869/wang_model/code/model_fitting/dask-worker-space/dask-worker-space/worker-jxur7ziv', purging
distributed.diskutils - INFO - Found stale lock file and directory '/users/k1201869/wang_model/code/model_fitting/dask-worker-space/dask-worker-space/worker-qpcp8w1r', purging
distributed.diskutils - INFO - Found stale lock file and directory '/users/k1201869/wang_model/code/model_fitting/dask-worker-space/dask-worker-space/worker-i24wl1j8', purging
distributed.worker - INFO -       Start worker at:    tcp://10.10.15.24:37472
distributed.worker - INFO -          Listening to:    tcp://10.10.15.24:37472
distributed.worker - INFO -          dashboard at:          10.10.15.24:44916
distributed.worker - INFO - Waiting to connect to:    tcp://10.10.17.12:40451
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    2.00 GB
distributed.worker - INFO -       Local Directory: /users/k1201869/wang_model/code/model_fitting/dask-worker-space/dask-worker-space/worker-_ykhz0wn
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - Waiting to connect to:    tcp://10.10.17.12:40451
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://10.10.15.24:37200 remote=tcp://10.10.17.12:40451>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://10.10.15.24:37212 remote=tcp://10.10.17.12:40451>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://10.10.15.24:37220 remote=tcp://10.10.17.12:40451>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://10.10.15.24:37224 remote=tcp://10.10.17.12:40451>
distributed.worker - INFO - Waiting to connect to:    tcp://10.10.17.12:40451
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://10.10.15.24:37242 remote=tcp://10.10.17.12:40451>
distributed.worker - INFO - Waiting to connect to:    tcp://10.10.17.12:40451
distributed.worker - INFO - Waiting to connect to:    tcp://10.10.17.12:40451
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://10.10.15.24:37392 remote=tcp://10.10.17.12:40451>
distributed.worker - INFO - Waiting to connect to:    tcp://10.10.17.12:40451
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://10.10.15.24:37438 remote=tcp://10.10.17.12:40451>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://10.10.15.24:37466 remote=tcp://10.10.17.12:40451>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://10.10.15.24:37498 remote=tcp://10.10.17.12:40451>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://10.10.15.24:37530 remote=tcp://10.10.17.12:40451>
distributed.nanny - INFO - Closing Nanny at 'tcp://10.10.15.24:42625'
distributed.worker - INFO - Stopping worker at tcp://10.10.15.24:37472
distributed.worker - INFO - Closed worker has not yet started: Status.undefined
distributed.dask_worker - INFO - End worker
Traceback (most recent call last):
  File "/users/k1201869/miniconda3/envs/python38/lib/python3.8/site-packages/distributed/core.py", line 295, in _
    await asyncio.wait_for(self.start(), timeout=timeout)
  File "/users/k1201869/miniconda3/envs/python38/lib/python3.8/asyncio/tasks.py", line 490, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/users/k1201869/miniconda3/envs/python38/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/users/k1201869/miniconda3/envs/python38/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/users/k1201869/miniconda3/envs/python38/lib/python3.8/site-packages/distributed/cli/dask_worker.py", line 460, in <module>
    go()
  File "/users/k1201869/miniconda3/envs/python38/lib/python3.8/site-packages/distributed/cli/dask_worker.py", line 456, in go
    main()
  File "/users/k1201869/miniconda3/envs/python38/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/users/k1201869/miniconda3/envs/python38/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/users/k1201869/miniconda3/envs/python38/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/users/k1201869/miniconda3/envs/python38/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/users/k1201869/miniconda3/envs/python38/lib/python3.8/site-packages/distributed/cli/dask_worker.py", line 442, in main
    loop.run_sync(run)
  File "/users/k1201869/miniconda3/envs/python38/lib/python3.8/site-packages/tornado/ioloop.py", line 532, in run_sync
    return future_cell[0].result()
  File "/users/k1201869/miniconda3/envs/python38/lib/python3.8/site-packages/distributed/cli/dask_worker.py", line 436, in run
    await asyncio.gather(*nannies)
  File "/users/k1201869/miniconda3/envs/python38/lib/python3.8/asyncio/tasks.py", line 684, in _wrap_awaitable
    return (yield from awaitable.__await__())
  File "/users/k1201869/miniconda3/envs/python38/lib/python3.8/site-packages/distributed/core.py", line 299, in _
    raise TimeoutError(
asyncio.exceptions.TimeoutError: Nanny failed to start in 60 seconds
